# Generated by Django 3.2.19 on 2023-06-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='case',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='cooler',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='graphics_card',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='memory',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='motherboard',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='operating_system',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='power_supply',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='processor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='storage',
            field=models.CharField(max_length=200),
        ),
    ]
